### PR TITLE
user manuals

### PR DESCRIPTION
**Pull request by coffeehousejazz**

### CODE REVIEW

**Comment by luctowers** [comment]
Is the the `-3` on the end of the alignment manual filename intended?

**Review by luctowers — COMMENTED** [review]
I don't think the licensing and cautions section really belongs in the user manuals tbh

**Comment by coffeehousejazz** [comment]
> I don't think the licensing and cautions section really belongs in the user manuals tbh

they do belong there

**Comment by coffeehousejazz** [comment]
> Is the the `-3` on the end of the alignment manual filename intended?

oops! fixed

**Review by luctowers — APPROVED** [review]
lgtm, thank you!

**Pull request merged**
